import UIKit
import UserNotifications

@main
final class AppDelegate: UIResponder, UIApplicationDelegate, UNUserNotificationCenterDelegate {
    var window: UIWindow?

    func application(_ application: UIApplication, didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey: Any]? = nil) -> Bool {
        UNUserNotificationCenter.current().delegate = self
        let window = UIWindow(frame: UIScreen.main.bounds)
        window.rootViewController = RootTabBarController()
        window.tintColor = UIColor(red: 0.878, green: 0.125, blue: 0.153, alpha: 1)
        window.makeKeyAndVisible(); self.window = window
        let launchOverlay = NinjaLaunchOverlay(frame: window.bounds)
        launchOverlay.autoresizingMask = [.flexibleWidth, .flexibleHeight]
        window.addSubview(launchOverlay); launchOverlay.play()
        return true
    }

    func userNotificationCenter(_ center: UNUserNotificationCenter, willPresent notification: UNNotification, withCompletionHandler completionHandler: @escaping (UNNotificationPresentationOptions) -> Void) { completionHandler([.banner, .list, .sound]) }
    func userNotificationCenter(_ center: UNUserNotificationCenter, didReceive response: UNNotificationResponse, withCompletionHandler completionHandler: @escaping () -> Void) { DispatchQueue.main.async { [weak self] in (self?.window?.rootViewController as? RootTabBarController)?.showAppointments(); completionHandler() } }
}

private final class NinjaLaunchOverlay: UIView {
    private enum Palette { static let background=UIColor(red:0.008,green:0.016,blue:0.012,alpha:1); static let red=UIColor(red:0.878,green:0.125,blue:0.153,alpha:1); static let green=UIColor(red:0.561,green:0.741,blue:0.180,alpha:1) }
    private let stage=UIView(), redHaze=CAGradientLayer(), greenHaze=CAGradientLayer(), aura=CAShapeLayer(), burst=CAShapeLayer(), orbit=CAShapeLayer(), redOrb=CAShapeLayer(), greenOrb=CAShapeLayer(), strikeGlow=CAShapeLayer(), strike=CAShapeLayer(), strikeTip=CAShapeLayer(), wordmarkMask=CAShapeLayer()
    private let mark=UIImageView(image:UIImage(named:"LaunchMark")), wordmark=UIImageView(image:UIImage(named:"SplashWordmark")); private var hasPlayed=false
    override init(frame:CGRect){super.init(frame:frame);backgroundColor=Palette.background;isUserInteractionEnabled=true;isAccessibilityElement=true;accessibilityViewIsModal=true;accessibilityLabel="Mosquito Ninja. Bite Back.";configureHaze(redHaze,color:Palette.red,peakAlpha:0.23,center:CGPoint(x:0.5,y:0.47));layer.addSublayer(redHaze);configureHaze(greenHaze,color:Palette.green,peakAlpha:0.07,center:CGPoint(x:0.5,y:0.52));layer.addSublayer(greenHaze);stage.isUserInteractionEnabled=false;addSubview(stage);configureCircle(aura,color:Palette.red.withAlphaComponent(0.18),lineWidth:0);aura.shadowColor=Palette.red.cgColor;aura.shadowOpacity=0.68;aura.shadowRadius=54;aura.opacity=0;stage.layer.addSublayer(aura);configureCircle(burst,color:Palette.red.withAlphaComponent(0.72),lineWidth:1);burst.fillColor=UIColor.clear.cgColor;burst.shadowColor=Palette.red.cgColor;burst.shadowOpacity=0.5;burst.shadowRadius=18;burst.opacity=0;stage.layer.addSublayer(burst);configureCircle(orbit,color:UIColor.white.withAlphaComponent(0.14),lineWidth:1);orbit.fillColor=UIColor.clear.cgColor;orbit.opacity=0;stage.layer.addSublayer(orbit);redOrb.fillColor=Palette.red.cgColor;redOrb.shadowColor=Palette.red.cgColor;redOrb.shadowOpacity=0.95;redOrb.shadowRadius=7;orbit.addSublayer(redOrb);greenOrb.fillColor=Palette.green.cgColor;greenOrb.shadowColor=Palette.green.cgColor;greenOrb.shadowOpacity=0.9;greenOrb.shadowRadius=7;orbit.addSublayer(greenOrb);mark.contentMode = .scaleAspectFit;mark.alpha=0;mark.layer.shadowColor=UIColor.black.cgColor;mark.layer.shadowOpacity=0.72;mark.layer.shadowRadius=24;mark.layer.shadowOffset=CGSize(width:0,height:18);stage.addSubview(mark);configureStrike(strikeGlow,width:18,opacity:0.46);configureStrike(strike,width:7,opacity:1);stage.layer.addSublayer(strikeGlow);stage.layer.addSublayer(strike);strikeTip.fillColor=UIColor.white.cgColor;strikeTip.shadowColor=Palette.red.cgColor;strikeTip.shadowOpacity=1;strikeTip.shadowRadius=15;strikeTip.opacity=0;stage.layer.addSublayer(strikeTip);wordmark.contentMode = .scaleAspectFit;wordmark.alpha=0;wordmark.layer.shadowColor=Palette.red.cgColor;wordmark.layer.shadowOpacity=0.22;wordmark.layer.shadowRadius=14;wordmark.layer.mask=wordmarkMask;addSubview(wordmark)}
    required init?(coder:NSCoder){fatalError("init(coder:) has not been implemented")}
    override func layoutSubviews(){super.layoutSubviews();let compact=bounds.height<560;let markSize=compact ? min(bounds.height*0.58,bounds.width*0.52):min(bounds.width*0.88,370);let ww=compact ? min(bounds.width*0.68,460):min(bounds.width*0.96,610);let wh=ww*(361.0/1080.0);let overlap:CGFloat=compact ? 28:34;let total=markSize+wh-overlap;let top=bounds.midY-total/2-(compact ? 0:bounds.height*0.02);stage.frame=CGRect(x:bounds.midX-markSize/2,y:top,width:markSize,height:markSize);mark.frame=stage.bounds;wordmark.frame=CGRect(x:bounds.midX-ww/2,y:stage.frame.maxY-overlap,width:ww,height:wh);redHaze.frame=bounds.insetBy(dx:-bounds.width*0.24,dy:-bounds.height*0.24);greenHaze.frame=bounds;[aura,burst,orbit,strikeGlow,strike,strikeTip].forEach{$0.frame=stage.bounds};let center=CGPoint(x:markSize/2,y:markSize/2);aura.path=UIBezierPath(ovalIn:stage.bounds.insetBy(dx:markSize*0.13,dy:markSize*0.13)).cgPath;burst.path=UIBezierPath(ovalIn:stage.bounds.insetBy(dx:markSize*0.08,dy:markSize*0.08)).cgPath;orbit.path=UIBezierPath(ovalIn:stage.bounds.insetBy(dx:0.5,dy:0.5)).cgPath;let rs=max(6,markSize*0.019);redOrb.path=UIBezierPath(ovalIn:CGRect(x:markSize*0.105,y:markSize*0.145,width:rs,height:rs)).cgPath;let gs=max(5,markSize*0.014);greenOrb.path=UIBezierPath(ovalIn:CGRect(x:markSize*0.915,y:markSize*0.745,width:gs,height:gs)).cgPath;let angle = -38.0*CGFloat.pi/180;let half=markSize*0.27;let sc=CGPoint(x:center.x,y:markSize*0.466);let delta=CGPoint(x:cos(angle)*half,y:sin(angle)*half);let start=CGPoint(x:sc.x-delta.x,y:sc.y-delta.y),end=CGPoint(x:sc.x+delta.x,y:sc.y+delta.y);let p=UIBezierPath();p.move(to:start);p.addLine(to:end);strikeGlow.path=p.cgPath;strike.path=p.cgPath;strikeGlow.lineWidth=max(13,markSize*0.049);strike.lineWidth=max(6,markSize*0.021);let tr=max(10,markSize*0.036);strikeTip.path=UIBezierPath(ovalIn:CGRect(x:end.x-tr,y:end.y-tr,width:tr*2,height:tr*2)).cgPath;wordmarkMask.frame=wordmark.bounds;wordmarkMask.path=UIBezierPath(rect:wordmark.bounds).cgPath}
    func play(){guard !hasPlayed else{return};hasPlayed=true;setNeedsLayout();layoutIfNeeded();if UIAccessibility.isReduceMotionEnabled{showReducedMotionSplash();return};animateAtmosphere();animateMark();animateStrike();animateWordmark();DispatchQueue.main.asyncAfter(deadline:.now()+0.82){NinjaHaptics.impact(.medium,intensity:0.9)};UIView.animate(withDuration:0.28,delay:2.12,options:[.curveEaseIn,.beginFromCurrentState]){self.alpha=0;self.transform=CGAffineTransform(scaleX:1.018,y:1.018)}completion:{_ in self.removeFromSuperview()}}
    private func configureCircle(_ l:CAShapeLayer,color:UIColor,lineWidth:CGFloat){l.fillColor=color.cgColor;l.strokeColor=color.cgColor;l.lineWidth=lineWidth}
    private func configureHaze(_ l:CAGradientLayer,color:UIColor,peakAlpha:CGFloat,center:CGPoint){l.type = .radial;l.colors=[color.withAlphaComponent(peakAlpha).cgColor,color.withAlphaComponent(peakAlpha*0.32).cgColor,UIColor.clear.cgColor];l.locations=[0,0.34,0.72];l.startPoint=center;l.endPoint=CGPoint(x:0.94,y:0.94);l.opacity=0}
    private func configureStrike(_ l:CAShapeLayer,width:CGFloat,opacity:Float){l.fillColor=UIColor.clear.cgColor;l.strokeColor=Palette.red.withAlphaComponent(CGFloat(opacity)).cgColor;l.lineWidth=width;l.lineCap = .round;l.shadowColor=Palette.red.cgColor;l.shadowOpacity=opacity;l.shadowRadius=width;l.strokeEnd=0}
    private func animateAtmosphere(){redHaze.opacity=1;animateScale(redHaze,values:[0.52,1],keyTimes:[0,1],duration:1.18,delay:0);animateOpacity(redHaze,values:[0,1],keyTimes:[0,1],duration:0.72,delay:0);greenHaze.opacity=0.7;animateOpacity(greenHaze,values:[0,0.7],keyTimes:[0,1],duration:0.9,delay:0.08);aura.opacity=0.82;animateScale(aura,values:[0.28,1.18,1],keyTimes:[0,0.55,1],duration:1.28,delay:0.03);animateOpacity(aura,values:[0,1,0.82],keyTimes:[0,0.55,1],duration:1.28,delay:0.03);burst.opacity=0;animateScale(burst,values:[0.25,1.72],keyTimes:[0,1],duration:0.72,delay:0.58);animateOpacity(burst,values:[0,0.72,0],keyTimes:[0,0.24,1],duration:0.72,delay:0.58);orbit.opacity=0.38;animateOpacity(orbit,values:[0,0.8,0.38],keyTimes:[0,0.42,1],duration:1.22,delay:0.05)}
    private func animateMark(){mark.alpha=1;let a=CAKeyframeAnimation(keyPath:"transform");a.values=[CATransform3DConcat(CATransform3DMakeScale(0.32,0.32,1),CATransform3DMakeRotation(-72*.pi/180,0,0,1)),CATransform3DConcat(CATransform3DMakeScale(1.08,1.08,1),CATransform3DMakeRotation(3*.pi/180,0,0,1)),CATransform3DIdentity];a.keyTimes=[0,0.52,1];a.duration=0.88;a.beginTime=CACurrentMediaTime()+0.06;a.fillMode = .backwards;a.timingFunction=CAMediaTimingFunction(controlPoints:0.14,0.76,0.18,1);mark.layer.add(a,forKey:"markEntrance");animateOpacity(mark.layer,values:[0,1,1],keyTimes:[0,0.46,1],duration:0.88,delay:0.06)}
    private func animateStrike(){let begin=CACurrentMediaTime()+0.62;[strikeGlow,strike].forEach{l in l.strokeEnd=1;let d=CABasicAnimation(keyPath:"strokeEnd");d.fromValue=0;d.toValue=1;d.duration=0.52;d.beginTime=begin;d.fillMode = .backwards;l.add(d,forKey:"strikeDraw");let f=CAKeyframeAnimation(keyPath:"opacity");f.values=[0,1,1,0];f.keyTimes=[0,0.12,0.72,1];f.duration=0.52;f.beginTime=begin;l.opacity=0;l.add(f,forKey:"strikeFade")};animateScale(strikeTip,values:[0.2,1,1.7],keyTimes:[0,0.35,1],duration:0.44,delay:0.68);animateOpacity(strikeTip,values:[0,1,0],keyTimes:[0,0.35,1],duration:0.44,delay:0.68)}
    private func animateWordmark(){wordmark.alpha=1;let a=CAKeyframeAnimation(keyPath:"transform");a.values=[CATransform3DConcat(CATransform3DMakeTranslation(0,14,0),CATransform3DMakeScale(0.94,0.94,1)),CATransform3DIdentity];a.keyTimes=[0,1];a.duration=0.68;a.beginTime=CACurrentMediaTime()+0.82;a.fillMode = .backwards;a.timingFunction=CAMediaTimingFunction(controlPoints:0.16,0.82,0.2,1);wordmark.layer.add(a,forKey:"wordmarkEntrance");animateOpacity(wordmark.layer,values:[0,1,1],keyTimes:[0,0.48,1],duration:0.68,delay:0.82);let start=CGRect(x:wordmark.bounds.midX-1,y:0,width:2,height:wordmark.bounds.height);let r=CABasicAnimation(keyPath:"path");r.fromValue=UIBezierPath(rect:start).cgPath;r.toValue=UIBezierPath(rect:wordmark.bounds).cgPath;r.duration=0.68;r.beginTime=CACurrentMediaTime()+0.82;r.fillMode = .backwards;wordmarkMask.add(r,forKey:"wordmarkReveal")}
    private func showReducedMotionSplash(){mark.alpha=1;redHaze.opacity=1;greenHaze.opacity=0.7;aura.opacity=0.82;orbit.opacity=0.38;wordmark.alpha=1;UIView.animate(withDuration:0.18,delay:0.42){self.alpha=0}completion:{_ in self.removeFromSuperview()}}
    private func animateScale(_ l:CALayer,values:[CGFloat],keyTimes:[NSNumber],duration:CFTimeInterval,delay:CFTimeInterval){let a=CAKeyframeAnimation(keyPath:"transform.scale");a.values=values;a.keyTimes=keyTimes;a.duration=duration;a.beginTime=CACurrentMediaTime()+delay;a.fillMode = .backwards;a.timingFunction=CAMediaTimingFunction(controlPoints:0.16,0.78,0.18,1);l.add(a,forKey:"scale-\(delay)")}
    private func animateOpacity(_ l:CALayer,values:[Float],keyTimes:[NSNumber],duration:CFTimeInterval,delay:CFTimeInterval){let a=CAKeyframeAnimation(keyPath:"opacity");a.values=values;a.keyTimes=keyTimes;a.duration=duration;a.beginTime=CACurrentMediaTime()+delay;a.fillMode = .backwards;l.add(a,forKey:"opacity-\(delay)")}
}
